# Generated by Django 4.1.2 on 2022-10-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='creadted',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='creadted',
            new_name='created',
        ),
    ]
